// Datos de la carta — La Tía Veneno
window.RESTAURANT = {
  name: "La Tía Veneno",
  tagline: "Sabor a Perú",
  city: "Chile",
  phone: "+56 945481249",
  whatsapp: "56945481249",
  address: "Rengo 10095 El Bosque, Santiago",
  hours: [
    { d: "Lun – Jue", h: "12:00 – 24:00" },
    { d: "Vie – Sáb", h: "12:00 – 24:00" },
    { d: "Domingo",   h: "12:00 – 22:00" },
  ],
  social: {
    instagram: "@latiaveneno",
    facebook: "latiaveneno",
  },
  testimonials: [
    { name: "Camila R.", stars: 5, text: "El mejor ceviche fuera de Lima. La leche de tigre es adictiva, vuelvo cada semana." },
    { name: "Diego P.",  stars: 5, text: "El lomo saltado tiene el wok justo, jugo perfecto y papa crocante. Atención impecable." },
    { name: "Valeria M.", stars: 5, text: "Pedí el Cevichop y me transportó. Maíz tostado, camote, todo en su punto." },
    { name: "Juan A.",   stars: 4, text: "Aeropuerto generoso para compartir. Volveré por el Tacu Tacu con lomo." },
  ],
  gallery: [
    "p1-08.jpeg",
    "p1-15.jpeg",
    "p1-09.jpeg",
    "p1-04.jpeg",
    "p2-03.jpeg",
    "p2-09.jpeg",
  ],
};

// Helper precios CLP
const p = (n) => n;

window.MENU = [
  {
    id: "entradas",
    name: "Entradas",
    icon: "🥑",
    blurb: "Para empezar la mesa con sabor peruano.",
    items: [
      { id:"papa-huanca",  name:"Papa a la Huancaína",       price:p(5200),  desc:"Papa amarilla bañada en crema de ají amarillo, queso fresco y leche evaporada. Aceituna y huevo.", img:"p2-05.jpeg", tags:["clásico","vegetariano"] },
      { id:"yuca-huanca",  name:"Yuca Frita a la Huancaína", price:p(5200),  desc:"Bastones de yuca dorada con nuestra salsa huancaína de la casa.", img:"p1-01.jpeg", tags:["vegetariano"] },
      { id:"ensalada-mix", name:"Ensalada Mixta",            price:p(5900),  desc:"Lechuga, tomate, palta, choclo baby y cebolla, con vinagreta de la casa.", img:"p1-04.jpeg", tags:["fresco","vegetariano"] },
      { id:"causa-limena", name:"Causa Limeña",              price:p(8000),  desc:"Pastel frío de papa amarilla con ají, palta y pollo deshilachado. Aceituna y huevo.", img:"p2-09.jpeg", tags:["clásico"] },
      { id:"causa-atun",   name:"Causa de Atún",             price:p(8000),  desc:"Capas de papa amarilla, palta y atún ligado en mayo casera.", img:"p1-02.jpeg" },
      { id:"causa-acev",   name:"Causa Acevichada",          price:p(10500), desc:"Causa rellena, coronada con ceviche de pescado y crema acevichada.", img:"p1-03.jpeg", tags:["popular"] },
    ],
  },
  {
    id: "ceviches",
    name: "Ceviches",
    icon: "🐟",
    blurb: "El frescor del Pacífico, en su punto cítrico.",
    items: [
      { id:"leche-tigre",   name:"Leche de Tigre",        price:p(7000),  desc:"Vaso del jugo madre del ceviche, con trozos de pescado, camarón y choclo tostado.", img:"p1-14.jpeg", tags:["fuerte"] },
      { id:"cevichop",      name:"Cevichop",              price:p(11500), desc:"Nuestra versión personal: ceviche cremoso de pescado y camarón, choclo tostado y chifle.", img:"p1-04.jpeg", tags:["de la casa","popular"] },
      { id:"ceviche-clasi", name:"Ceviche Clásico",       price:p(12400), desc:"Pescado fresco curtido en limón, ají limo, cebolla morada, camote y choclo.", img:"p1-05.jpeg", tags:["clásico"] },
      { id:"ceviche-mixto", name:"Ceviche Mixto",         price:p(13200), desc:"Pescado, camarón, calamar y pulpo en leche de tigre clásica.", img:"p1-06.jpeg" },
      { id:"ceviche-carre", name:"Ceviche Carretillero",  price:p(14900), desc:"Mixto + chicharrón de pescado y calamar apanado. El plato más generoso de la carta.", img:"p1-07.jpeg", tags:["recomendado"] },
    ],
  },
  {
    id: "chicharrones",
    name: "Chicharrones",
    icon: "🍤",
    blurb: "Crocante por fuera, jugoso por dentro.",
    items: [
      { id:"chicha-jibia",   name:"Chicharrón de Jibia",    price:p(9800),  desc:"Tiras de jibia rebozada y frita, con salsa tártara y limón.", img:"p1-08.jpeg" },
      { id:"chicha-pescado", name:"Chicharrón de Pescado",  price:p(11500), desc:"Pescado blanco apanado en chuño, frito al momento. Yuca y salsa golf.", img:"p1-09.jpeg", tags:["popular"] },
      { id:"chicha-camaron", name:"Chicharrón de Camarón",  price:p(13800), desc:"Camarones apanados, dorados, con tártara cítrica.", img:"p1-10.jpeg" },
      { id:"jalea-mixta",    name:"Jalea Mixta",            price:p(19800), desc:"Tabla peruana: pescado, calamar, camarón y jibia fritos. Para compartir.", img:"p1-11.jpeg", tags:["compartir","XL"] },
    ],
  },
  {
    id: "tradicion",
    name: "Tradición Peruana",
    icon: "🌶️",
    blurb: "Los grandes clásicos del wok criollo.",
    items: [
      { id:"pollo-saltado",   name:"Pollo Saltado",                       price:p(9900),  desc:"Pollo al wok con cebolla, tomate y ají amarillo. Arroz y papas fritas.", img:"p1-09.jpeg" },
      { id:"lomo-saltado",    name:"Lomo Saltado",                        price:p(11900), desc:"Lomo de res al wok con sillao, vinagre tinto y ají. Papas y arroz graneado.", img:"p1-10.jpeg", tags:["clásico","popular"] },
      { id:"saltado-3sab",    name:"Saltado 3 Sabores",                   price:p(13800), desc:"Lomo, pollo y camarón al wok con todas las verduras. Arroz y papa.", img:"p1-12.jpeg" },
      { id:"tall-salt-pollo", name:"Tallarín Saltado Pollo",              price:p(9800),  desc:"Tallarín al wok con pollo, sillao y verduras crocantes.", img:"p2-08.jpeg" },
      { id:"tall-salt-carne", name:"Tallarín Saltado Carne",              price:p(11500), desc:"Lomo de res al wok sobre tallarín fresco.", img:"p1-05.jpeg" },
      { id:"tall-salt-cama",  name:"Tallarín Saltado Camarones",          price:p(12900), desc:"Camarones al wok, tallarín y crema picante a la huancaína.", img:"p1-13.jpeg" },
      { id:"tall-salt-mix",   name:"Tallarín Saltado Mixto",              price:p(12500), desc:"Pollo + carne + camarón al wok sobre tallarín fresco.", img:"p1-03.jpeg" },
      { id:"picante-mar",     name:"Picante de Mariscos",                 price:p(10300), desc:"Guiso peruano de pescado y mariscos en salsa cremosa de ají.", img:"p2-01.jpeg" },
      { id:"pescado-macho",   name:"Pescado a lo Macho",                  price:p(11500), desc:"Filete de pescado bañado en salsa cremosa con calamar y camarón.", img:"p2-02.jpeg", tags:["recomendado"] },
      { id:"mar-tierra",      name:"Mar y Tierra",                        price:p(15200), desc:"Lomo a la parrilla + camarones y calamar en salsa de la casa.", img:"p1-20.jpeg", tags:["XL"] },
      { id:"reineta-camaron", name:"Reineta en Salsa de Camarones",       price:p(13200), desc:"Filete de reineta cubierto con salsa cremosa de camarones.", img:"p1-18.jpeg" },
      { id:"pollo-crispy",    name:"Pollo Crispy",                        price:p(9800),  desc:"Pollo apanado al estilo casero, arroz, papas y ensalada.", img:"p1-13.jpeg" },
      { id:"aji-gallina",     name:"Ají de Gallina",                      price:p(9800),  desc:"Pollo deshilachado en crema de ají amarillo. Arroz, huevo y aceituna.", img:"p2-03.jpeg", tags:["clásico"] },
      { id:"milanesa-pollo",  name:"Milanesa de Pollo",                   price:p(9800),  desc:"Milanesa apanada al momento, arroz, papas y ensalada fresca.", img:"p1-01.jpeg" },
      { id:"pollo-plancha",   name:"Pollo a la Plancha",                  price:p(9800),  desc:"Pechuga marinada a la plancha, arroz y guarnición.", img:"p1-14.jpeg" },
      { id:"reineta-plancha", name:"Reineta a la Plancha",                price:p(9800),  desc:"Reineta a la plancha con limón, arroz blanco y papas.", img:"p1-15.jpeg" },
    ],
  },
  {
    id: "pastas",
    name: "Pastas",
    icon: "🍝",
    blurb: "Pasta fresca con alma peruana.",
    items: [
      { id:"alfredo",      name:"Tallarines a lo Alfredo",                        price:p(8800),  desc:"Tallarín en crema de queso parmesano y jamón.", img:"p1-11.jpeg" },
      { id:"pesto",        name:"Tallarín al Pesto",                              price:p(10900), desc:"Pesto a la peruana de albahaca y espinaca, sobre tallarín. Filete encima opcional.", img:"p1-17.jpeg", tags:["vegetariano"] },
      { id:"blanca-champ", name:"Tallarines Salsa Blanca y Champiñón",           price:p(10200), desc:"Crema de champiñones y un toque de queso azul.", img:"p1-12.jpeg" },
      { id:"lomo-huanca",  name:"Lomo Saltado con Tallarines a la Huancaína",    price:p(11900), desc:"Lomo al wok sobre tallarines bañados en huancaína. Especialidad.", img:"p1-16.jpeg", tags:["recomendado"] },
    ],
  },
  {
    id: "arroces",
    name: "Arroces y Chaufas",
    icon: "🍚",
    blurb: "El wok caliente, el arroz suelto.",
    items: [
      { id:"chaufa-pollo",  name:"Chaufa de Pollo",                price:p(9200),  desc:"Arroz al wok con pollo, sillao, kion y verdeo.", img:"p1-16.jpeg" },
      { id:"chaufa-carne",  name:"Chaufa de Carne",                price:p(10500), desc:"Arroz al wok con lomo de res, huevo y verdeo.", img:"p1-17.jpeg" },
      { id:"chaufa-mar",    name:"Chaufa de Mariscos",             price:p(11500), desc:"Arroz al wok con pulpo, calamar y camarón.", img:"p1-18.jpeg" },
      { id:"chaufa-cama",   name:"Chaufa de Camarones",            price:p(11800), desc:"Arroz al wok con camarones rosados y verdeo.", img:"p1-19.jpeg" },
      { id:"chaufa-mix",    name:"Chaufa Especial Mixto",          price:p(12500), desc:"Pollo, carne y mariscos al wok. La estrella del chifa.", img:"p1-20.jpeg", tags:["popular"] },
      { id:"aeropuerto",    name:"Aeropuerto Clásico",             price:p(10500), desc:"Tallarín + arroz chaufa juntos al wok. Para los que no eligen.", img:"p2-01.jpeg", tags:["XL","compartir"] },
      { id:"risotto-huan",  name:"Risotto Huancaína con Lomo",     price:p(12500), desc:"Arroz cremoso a la huancaína con lomo saltado encima.", img:"p1-06.jpeg" },
      { id:"risotto-cama",  name:"Risotto con Salsa de Camarones", price:p(10900), desc:"Arroz cremoso bañado en salsa de camarones.", img:"p1-15.jpeg" },
      { id:"tacu-lomo",     name:"Tacu Tacu con Lomo",             price:p(12200), desc:"Tacu tacu de frejol y arroz, con lomo saltado.", img:"p1-06.jpeg", tags:["clásico"] },
      { id:"tacu-mar",      name:"Tacu Tacu con Picante de Mariscos", price:p(12200), desc:"Tacu tacu coronado con picante de mariscos.", img:"p2-01.jpeg" },
    ],
  },
  {
    id: "especial",
    name: "Especial Tía Veneno",
    icon: "💜",
    blurb: "Recetas firmadas por la casa.",
    items: [
      { id:"salt-veg",      name:"Saltado Vegetariano",                    price:p(9200),  desc:"Wok de proteína vegetal con verduras y arroz. Aromático y picante a pedido.", img:"p2-02.jpeg", tags:["vegetariano"] },
      { id:"arroz-mar",     name:"Arroz con Mariscos",                     price:p(12000), desc:"Arroz peruano con mariscos en su tinta y ají amarillo.", img:"p1-15.jpeg" },
      { id:"chaufa-lomo",   name:"Chaufa con Lomo",                        price:p(13900), desc:"Nuestra chaufa con un generoso lomo saltado encima.", img:"p2-03.jpeg", tags:["recomendado"] },
      { id:"pesc-blanca",   name:"Pescado en Salsa Blanca",                price:p(10200), desc:"Filete a la plancha en salsa blanca al limón. Arroz y papa.", img:"p1-19.jpeg" },
      { id:"pesc-blanca-c", name:"Pescado en Salsa Blanca con Champiñón", price:p(10600), desc:"Filete a la plancha con crema de champiñones.", img:"p1-12.jpeg" },
    ],
  },
  {
    id: "guarniciones",
    name: "Frituras y Guarniciones",
    icon: "🍟",
    blurb: "Acompañamientos y antojos.",
    items: [
      { id:"papa-frita",   name:"Porción de Papa",     price:p(4500), desc:"Papas fritas crocantes.", img:"p2-12.jpeg" },
      { id:"salchipapa",   name:"Salchipapa",          price:p(5500), desc:"Papas fritas con salchicha y salsas.", img:"p2-04.jpeg" },
      { id:"salchipapa-x", name:"Salchipapa Especial", price:p(6500), desc:"Con salchicha, pollo, huevo y salsas.", img:"p2-12.jpeg", tags:["popular"] },
      { id:"nuggets",      name:"Nuggets de Pollo",    price:p(8500), desc:"Bastones de pollo apanados con papas y salsas.", img:"p1-13.jpeg" },
      { id:"ajinomen",     name:"Sopa Ajinomen",       price:p(6000), desc:"Fideo en caldo aromatizado a la peruana.", img:"p2-05.jpeg" },
      { id:"arroz-porc",   name:"Porción de Arroz",    price:p(2200), desc:"Arroz blanco graneado.", img:"p2-11.jpeg" },
      { id:"papa-dor",     name:"Papas Doradas",       price:p(2200), desc:"Papas salteadas en mantequilla.", img:"p1-12.jpeg" },
      { id:"papa-rust",    name:"Papas Rústicas",      price:p(4500), desc:"Papas con cáscara, sal y orégano.", img:"p2-10.jpeg" },
    ],
  },
  {
    id: "bebidas",
    name: "Bebidas",
    icon: "🥤",
    blurb: "Para refrescar la mesa.",
    items: [
      { id:"ik-600",   name:"Inka Kola 600ml",   price:p(2000), desc:"La bebida amarilla del Perú.", tags:["peruana"] },
      { id:"ik-15",    name:"Inka Kola 1.5L",    price:p(5200), desc:"Para compartir." },
      { id:"ik-gor",   name:"Inka Kola Gordita", price:p(3200), desc:"Botella personal grande." },
      { id:"cc-lata",  name:"Coca Cola Lata",    price:p(1800) },
      { id:"cc-15",    name:"Coca Cola 1.5L",    price:p(4200) },
      { id:"sprite",   name:"Sprite Lata",       price:p(1800) },
      { id:"fanta",    name:"Fanta Lata",        price:p(1800) },
      { id:"pepsi",    name:"Pepsi Lata",        price:p(1800) },
      { id:"bilz",     name:"Bilz Lata",         price:p(1800) },
    ],
  },
  {
    id: "alcohol",
    name: "Cervezas y Vinos",
    icon: "🍷",
    blurb: "Maridaje para tu mesa.",
    items: [
      { id:"corona",     name:"Corona",              price:p(2500) },
      { id:"heineken",   name:"Heineken",            price:p(2500) },
      { id:"royal",      name:"Royal Premium",       price:p(2500) },
      { id:"kunst",      name:"Kunstmann Torobayo",  price:p(3800), tags:["chilena"] },
      { id:"cusquena",   name:"Cusqueña 620ml",      price:p(4500), tags:["peruana"] },
      { id:"corona-g",   name:"Corona Grande",       price:p(4500) },
      { id:"heineken-1", name:"Heineken 1L",         price:p(4500) },
      { id:"michelada",  name:"Michelada",           price:p(1000), desc:"Adicional a cualquier cerveza." },
      { id:"copa-vino",  name:"Copa de Vino",        price:p(2800) },
      { id:"misiones",   name:"Misiones de Rengo",   price:p(7500), desc:"Botella." },
      { id:"casillero",  name:"Casillero del Diablo", price:p(8500), desc:"Botella." },
      { id:"diablo",     name:"Diablo",              price:p(15000), desc:"Botella reserva.", tags:["premium"] },
    ],
  },
];
